[workspace]
members = [
    "rust-pixel",
    "tools/*",
    "games/*",
]
exclude = [
    "games/poker/ffi",
    "games/poker/wasm",
    "games/template/ffi",
    "games/template/wasm",
]
resolver = "2"

[workspace.package]
authors = ["zipxing@hotmail.com"]
description = "2d pixel artgame engine & rapid prototype tools..."

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
